initial commit
Ihmoda/curriculum pull request #15
Opened 2018-02-18 16:30 UTC by Ihmoda

2018-02-20 05:17 UTC, songz commented on curriculum/js2/3.js
> +  isPrime,
no need to export this.

2018-02-20 05:18 UTC, songz commented on curriculum/js2/3.js
> +const isPrime = (num, val = 2) => {
instead of writing this over again, try importing it. `const {isPrime} = require('../js1/6.js');` Is it problem 6? I forgot.

2018-02-22 00:17 UTC, seemcat requested changes

2018-02-22 00:44 UTC, Ihmoda commented on curriculum/js2/3.js
This is curriculum/js2/3.js
 * Given an array, return an array of the same length
 *   where all elements that are not prime is changed to 1

2018-02-22 03:51 UTC, Ihmoda commented
Original Problem: 

/**
 * Given an array, return an array of the same length
 *   where all elements that are not prime is changed to 1
 * @param {array} a
 * @returns {array}
 */

const solution = (a) => {
  return [];
};

module.exports = {
  solution,
};

2018-02-22 21:57 UTC, songz commented on curriculum/js2/3.js
> +let isPrime = require('../js1/7.js').solution;
always use `const` unless you can't.

2018-02-22 22:33 UTC, songz commented on curriculum/js2/3.js
> +  if (idx === a.length) {
if your `if` condition only has one line, you don't need `{}`. so your code could be as simple as:
```
const solution = (a, idx = 0) => {
  if(idx === a.length) return a;
  if(!isPrime(a[idx])) a[idx] = 1;
  return solution (a, idx + 1);
}
```

2018-02-22 22:33 UTC, songz approved these changes

2018-02-22 22:37 UTC, merged